package com.college.attendance.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Entity
@Table(
        name = "face_embeddings",
        indexes = {
                @Index(
                        name = "idx_face_user_id",
                        columnList = "user_id"
                )
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FaceEmbedding {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * One face belongs to one system user.
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(
            name = "user_id",
            nullable = false,
            unique = true
    )
    private User user;

    /**
     * Face embedding generated by DeepFace.
     */
    @Lob
    @Column(
            nullable = false,
            columnDefinition = "LONGTEXT"
    )
    private String embedding;

    @Column(
            name = "embedding_size",
            nullable = false
    )
    private Integer embeddingSize;

    @Column(
            name = "model_name",
            nullable = false
    )
    private String modelName;

    @Column(name = "detector_backend")
    private String detectorBackend;

    @Column(
            nullable = false,
            length = 20
    )
    private String status;

    @Column(
            name = "registered_at",
            nullable = false
    )
    private LocalDateTime registeredAt;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;


    @PrePersist
    protected void onCreate() {

        LocalDateTime now = LocalDateTime.now();

        if (status == null) {
            status = "ACTIVE";
        }

        if (registeredAt == null) {
            registeredAt = now;
        }

        if (createdAt == null) {
            createdAt = now;
        }
    }


    @PreUpdate
    protected void onUpdate() {

        updatedAt = LocalDateTime.now();
    }
}